server:
  port: 13031
  shutdown: graceful

spring:
  profiles:
    active: local
    group:
      local:
        - console-logging # 콘솔 로깅만 사용
      test:
        - console-logging
      prod:
        - console-logging
        - console-logging
    include:
      - console-logging
  application:
    name: quartz
  # H2 Setting Info (H2 Console에 접속하기 위한 설정정보 입력)
  h2:
    console:
      enabled: true  # H2 Console을 사용할지 여부 (H2 Console은 H2 Database를 UI로 제공해주는 기능)
      path: /h2-console  # H2 Console의 Path
  # Database Setting Info (Database를 H2로 사용하기 위해 H2연결 정보 입력)
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver  # Database를 H2로 사용하겠다.
#    url: jdbc:mariadb://192.168.0.3:3306/quartz
#    username: root  # H2 접속 시 입력할 username 정보 (원하는 것으로 입력)
#    password: mariadb12!@ # H2 접속 시 입력할 password 정보 (원하는 것으로 입력)
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
